CREATE TABLE attendance (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    class_id INTEGER NOT NULL REFERENCES classes(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    checked_in_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
